name: jekyll-deploy-gh-pages
            
on:
  push:
    branches:
      - main # or master before October 2020

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: BryanSchuetz/jekyll-deploy-gh-pages@v2.0
        with:                                # Some relative inputs of your action
          token: ${{ secrets.GITHUB_TOKEN }}
